### ISSUE TITLE
Cannot set property 'path' of undefined

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/vinyl-fs-vpath#79]
Cause of this issue is unclear (I'm fuzzy on the logic). Caused by a bad assumption that a file will always be found (fundamentally wrong, the filesystem does not get process locked).

Stack trace from UserFrosting chat;
```
(node:75112) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'path' of undefined
    at VinylFsVPathSrc._read (/UserFrosting/build/node_modules/@userfrosting/vinyl-fs-vpath/dist/src.js:46:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:75112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[09:07:14] The following tasks did not complete: build
[09:07:14] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ uf-bundle: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ uf-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Silic0nS0ldier** [comment]
Could be caused by a case sensitive file system maybe?

**Comment by Silic0nS0ldier** [comment]
File system contents can change during execution, unlikely to be cause of this issue however we currently do not handle this. We should;

1. Emit a warning that a previously resolved file is no longer present and will not be included in the stream.
2. Move onto the next file or end stream as appropriate.

OR

Make the current behaviour canon, and provide a better error.

**Comment by Silic0nS0ldier** [comment]
Stack trace with error reporting improvements.
```
(node:3868) UnhandledPromiseRejectionWarning: FileGoneError:  - {"resolvedPath":"\\UserFrosting\\app\\sprinkles\\site\\assets\\pages\\img\\iStock-590597188 [Converted].png","virtualPath":"\\UserFrosting\\public\\assets\\pages\\img\\iStock-590597188 [Converted].png"}
    at VinylFsVPathSrc._read (\UserFrosting\build\node_modules\@userfrosting\vinyl-fs-vpath\dist\src.js:58:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[07:12:37] The following tasks did not complete: build
[07:12:37] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ uf-bundle: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ uf-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Silic0nS0ldier** [comment]
Thought I had documented this before but it seems I was mistaken. The cause is `[` and `]` having special meaning to `vinyl-fs` which takes a `glob` input. The fix here is to escape the file path.

**Comment by Silic0nS0ldier** [comment]
Resolved by https://github.com/userfrosting/vinyl-fs-vpath/pull/190
